### ISSUE TITLE
Moving built-in primitive types to separate M3

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-typescript#28]
When looking at the serialization of the LionCore M3 I noticed the presence of the primitive types: https://github.com/LIonWeb-org/lioncore-typescript/blob/da815075bd0f14d0fdcc17c5d37a0bcf9320029c/models/lioncore.json#L26

In the Java implementation I have two metamodels: one is LionCore and then there is a separate one that contains exclusively the built-in primitive types and it could later contain other built-ins we may need. In the Java implementation this is the M3 with built-ins: https://github.com/LIonWeb-org/lioncore-java/blob/master/core/src/main/java/org/lionweb/lioncore/java/metamodel/LionCoreBuiltins.java

I personally think that it makes sense to considerate built-ins as separate, as they are not the same as Concept, Metamodel, Property, etc. On the other hand I understand that we will always distribute the two metamodels together and the two are needed to provide the self definition of LionCore, so I can see the argument for merging them.

What do you think? Is this something that should be discussed with everyone?

**Comment by dslmeinte** [comment]
I agree, and I was already in the process of separating them. Just need to flesh out some details.

**Comment by dslmeinte** [comment]
See branch: https://github.com/LIonWeb-org/lioncore-typescript/compare/main...feature/stdlib-with-primitive-types

**Comment by dslmeinte** [comment]
Done as per PR #29
