### ISSUE TITLE
Question: are metamodels used in serialization implicit?

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-typescript#32]
If I look at [this file](https://github.com/LIonWeb-org/lioncore-typescript/blob/main/models/library.json) it is specifying nodes with types such as `LIonCore_M3_Metamodel` or `LIonCore_M3_PrimitiveType`. In general, should we declare with metamodels are we using? Is LionCore itself a special implicit metamodel and others should be declared?
I think it would be useful to know which metamodels are used by reading an header, so I could either reject the model, if I do not know how to handle that metamodel, or do initialization steps to load such metamodel

**Comment by dslmeinte** [comment]
No, this is going to be explicit, as in PR #29 - see e.g. [this file location](https://github.com/LIonWeb-org/lioncore-typescript/blob/214e606d0323be722a14d0fd4fbf0376f2d221d6/models/library.json#L18). (Feel free to review that PR.)

**Comment by enikao** [comment]
Relates to https://github.com/LIonWeb-org/organization/issues/50

**Comment by dslmeinte** [comment]
fixed through commit 65d86a6

**Comment by enikao** [comment]
Did you discuss whether we want to list _used_ metamodels explicitly in serialization? E.g. in a serialized M1 model, do we explicitly list all M2 metamodels referred to by `concept`, `properties`, `children`, `references`, etc?

**Comment by dslmeinte** [comment]
No, we didn't discuss it. I think we interpreted `dependsOn` similar to a model import. I think a `dependsOn` that points to specific metamodels (of languages) should maybe go in a separate feature, such as `conformsTo`?

**Comment by enikao** [comment]
Good idea: https://github.com/LIonWeb-org/organization/issues/76
