### ISSUE TITLE
Implement a concrete syntax for M3

### ISSUE THREAD

**Issue by dslmeinte** [LIonWeb-org/lioncore-typescript#35]
using Freon

**Comment by ftomassetti** [comment]
Should this be part of a separate component, for modularity?

**Comment by dslmeinte** [comment]
Yup. I'm not sure whether that separate component should be in a separate repository as well (or not), which is my I made it an issue here.

**Comment by dslmeinte** [comment]
Done by @joswarmer, as https://github.com/LIonWeb-org/lioncore-freon
