### ISSUE TITLE
Serialization of primitive properties

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-typescript#38]
While working on serialization I noticed that some property values (in particular boolean properties) are serialized as JSON booleans (e.g., `true` or `false`). My understanding is that all property values should be serialized as strings (e.g., `"true"` or `"false"`), so when copying https://github.com/LIonWeb-org/lioncore-typescript/blob/main/models/library.json into the lioncore-java repository I have changed those values.

I am opening the issue to discuss how to converge on this point.

**Comment by dslmeinte** [comment]
Let's discuss on Wednesday.

**Comment by dslmeinte** [comment]
Result: yes, all primitive values should be serialized as strings (including JSON).

**Comment by dslmeinte** [comment]
fixed by commit 45c8912

**Comment by enikao** [comment]
Is there anything from your discussion to add to https://github.com/LIonWeb-org/organization/issues/34, especially regarding rationale?

**Comment by dslmeinte** [comment]
It seems not. Maybe the biggest thing is that `JSON` is to be `JSON.stringify`-d at serialization and then `JSON.parse`-d at deserialization.
