### ISSUE TITLE
Differences in serialization schema

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-typescript#44]
[Here](https://github.com/LIonWeb-org/organization/blob/0d767567e9ccc191d3a787d8c9b19a8a7979e9c2/lioncore/serialization.adoc) the value for `serializationFormatVersion` is indicated as a string, while in the schema in this repository it is indicated as a number.

I think that string can be more general, but I can live with using a number.

I have noticed that while running the integration tests (the Java serialization is not compatible with the JSON schema in this repository)

**Comment by dslmeinte** [comment]
I'll change the TS impl. to `"1"`. The reason to use strings for primitive values everywhere holds for this as well.
