### ISSUE TITLE
Support the browser?

### ISSUE THREAD

**Issue by ftomassetti** [LIonWeb-org/lioncore-typescript#5]
Should we expect to be able to use LioncoreTS also in the browser?

**Comment by dslmeinte** [comment]
Eventually: yes. At the moment: not yet, because I'm targeting Deno first for (my own) dev convenience.

**Comment by dslmeinte** [comment]
We should be able to use something like https://esbuild.github.io to bundle for the Web and/or NPM.

**Comment by ftomassetti** [comment]
Great!

**Comment by dslmeinte** [comment]
(See also https://deno.land/manual@v1.29.1/tools/bundler)

**Comment by dslmeinte** [comment]
Merged into #9.
