### ISSUE TITLE
Publish as package for Deno, Node, and the browser

### ISSUE THREAD

**Issue by dslmeinte** [LIonWeb-org/lioncore-typescript#9]
Involves:

- Defining what to expose in `src/index.ts`
- Publish as Deno package - see https://deno.land/manual@v1.29.1/advanced/publishing
- Setting up bundling with e.g. https://esbuild.github.io/ for NPM
  - Bundle to `dist/` which also contains NPM metadata?
  - See also https://deno.land/manual@v1.29.1/advanced/publishing/dnt

This issue replaces issues #1 and #5.

**Comment by alessiostalla** [comment]
I've tried using the NPM package in the browser with several shims, but it doesn't seem possible right now. The deno-shim package requires and uses many Node APIs. In particular, now I'm stuck at 
```
mainModule.js:8 Uncaught TypeError: (0 , url_1.pathToFileURL) is not a function
    at ../node_modules/@deno/shim-deno/dist/deno/stable/variables/mainModule.js (mainModule.js:8:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../node_modules/@deno/shim-deno/dist/deno/stable/variables.js (variables.js:37:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../node_modules/@deno/shim-deno/dist/deno/stable/functions/chdir.js (chdir.js:10:1)
    at options.factory (react refresh:6:1)
```

b/c the "url" package [doesn't include Node's `pathToFileURL` function](https://github.com/defunctzombie/node-url/issues/63).

The main problem seems to be that Deno's Node shim is monolithic and uses all sorts of Node APIs, which doesn't play nice with the browser.

**Comment by alessiostalla** [comment]
`parse` uses the Deno XML module which in turn uses fs, etc.
I think "dnt" is already taking care of separating the tests from the production code. 
Funny that my spell-checker insists correcting "dnt" to "don't" 🤣

**Comment by dslmeinte** [comment]
Ironic that something (XML parsing) that should be really very portable is an obstacle to portability now...

We can also separate out the parsing-part of the Ecore-importer, keeping just the types that an XML parser is supposed to return, with the remark that the XML parser currently used is compatible with that. What do you think?

**Comment by alessiostalla** [comment]
Yes, we could try that and see if it improves.

**Comment by dslmeinte** [comment]
OK, I'll try and do that first, then.

By the way: how do you check whether the package works in the browser? Can we integrate that into this repository?

**Comment by alessiostalla** [comment]
Currently, I have another project where I manually add the Lioncore dependency and open a demo page in a browser. That could be automated, I think.

**Comment by dslmeinte** [comment]
If you have some time and opportunity, it'd be great (“stallar” even 😄) if you could add that!

**Comment by dslmeinte** [comment]
I split off the test code and its dependency management to a separate directory in this branch: https://github.com/LIonWeb-org/lioncore-typescript/tree/node-compatibility

Can you check whether that'd already solve some of the problems? The next step would probably be to modify `build_npm.ts` to not “drag in” any test dependency, right?

**Comment by dslmeinte** [comment]
Depends on the shed! 😆  (Incidentally: in Dutch “stal” means the same thing, including the derogatory association.)

**Comment by alessiostalla** [comment]
Cool!
Your branch appears to be solving the problem, yay! At least I can instantiate a node and obtain a Concept. We'll see going forward what's there to be added/removed in the module's exports.

**Comment by dslmeinte** [comment]
OK, I'll just merge that branch into `main`, and see whether the integration tests have a problem.

**Comment by ftomassetti** [comment]
Very happy about this one!
